import React, { useRef } from "react";

// Section Title Component
const SectionTitle = ({ number, title }) => (
  <div className="mt-4">
    <h3 className="text-base font-semibold text-heading">
      {number} {title}
    </h3>
  </div>
);

// Cover Section
const CoverSection = ({ cover }) => (
  <div className="mb-6 text-center">
    <div className="text-xs uppercase text-gray-500">
      Software Requirements Specification
    </div>
    <h1 className="text-2xl font-bold mt-2 text-heading">{cover.projectName}</h1>
    <p className="mt-2 text-sm text-gray-600">{cover.description}</p>

    <div className="mt-4">
      <div className="text-sm text-primary">
        <strong>Group Members:</strong> {cover.members.join(", ")}
      </div>
      <div className="text-sm text-gray-500">Date: {cover.date}</div>
    </div>
  </div>
);

// Introduction Section
const IntroductionSection = ({ introduction }) => (
  <>
    <SectionTitle number="1." title="Introduction" />
    <div className="pl-4">
      <h4 className="font-medium mt-2 text-primary">1.1 Purpose</h4>
      <p className="mt-1 text-primary/70">{introduction.purpose}</p>

      <h4 className="font-medium mt-2 text-primary">1.2 Scope</h4>
      <p className="mt-1 text-primary/70">{introduction.scope}</p>

      <h4 className="font-medium mt-2 text-primary">1.3 Definitions, Acronyms, and Abbreviations</h4>
      <ul className="list-disc ml-6 mt-1 text-primary/70">
        {introduction.definitions.map((d, i) => (
          <li key={i}>
            <strong>{d.term}:</strong> {d.meaning}
          </li>
        ))}
      </ul>

      <h4 className="font-medium mt-2 text-primary">1.4 References</h4>
      <p className="mt-1 text-primary/70">{introduction.references}</p>
    </div>
  </>
);

// General Description Section
const GeneralDescriptionSection = ({ generalDescription }) => (
  <>
    <SectionTitle number="2." title="General Description" />
    <div className="pl-4">
      <h4 className="font-medium mt-2 text-primary">2.1 Product Perspective</h4>
      <p className="mt-1 text-primary/70">{generalDescription.productPerspective}</p>

      <h4 className="font-medium mt-2 text-primary">2.2 Product Functions</h4>
      <p className="mt-1 text-primary/70">{generalDescription.productFunctions}</p>

      <h4 className="font-medium mt-2 text-primary">2.3 User Characteristics</h4>
      <p className="mt-1 text-primary/70">{generalDescription.userCharacteristics}</p>

      <h4 className="font-medium mt-2 text-primary">2.4 General Constraints</h4>
      <p className="mt-1 text-primary/70">{generalDescription.generalConstraints}</p>

      <h4 className="font-medium mt-2 text-primary">2.5 Assumptions and Dependencies</h4>
      <p className="mt-1 text-primary/70">{generalDescription.assumptionsDependencies}</p>
    </div>
  </>
);

// Specific Requirements Section
const SpecificRequirementsSection = ({ specificRequirements }) => (
  <>
    <SectionTitle number="3." title="Specific Requirements" />
    <div className="pl-4">
      <h4 className="font-medium mt-2 text-primary">3.1 Functional Requirements</h4>
      <ol className="list-decimal ml-6 mt-1 text-primary/70">
        {specificRequirements.functionalRequirements.map((fr, i) => (
          <li key={i} className="mb-1">{fr}</li>
        ))}
      </ol>

      <h4 className="font-medium mt-2 text-primary">3.2 External Interface Requirements</h4>
      <p className="mt-1 text-primary/70">{specificRequirements.externalInterfaceRequirements}</p>

      <h4 className="font-medium mt-2 text-primary">3.3 Non-Functional Requirements</h4>
      <ul className="list-disc ml-6 mt-1 text-primary/70">
        {specificRequirements.nonFunctionalRequirements.map((nfr, i) => (
          <li key={i} className="mb-1">{nfr}</li>
        ))}
      </ul>
    </div>
  </>
);

// Main Preview Component
export default function Preview({ content }) {
  const reportRef = useRef();

  if (!content) return null;

  const { cover, introduction, generalDescription, specificRequirements } = content;

  return (
    <div className="bg-background text-primary">
      <div ref={reportRef} className="text-sm leading-relaxed text-gray-800">
        <CoverSection cover={cover} />
        <hr className="my-4" />
        <IntroductionSection introduction={introduction} />
        <GeneralDescriptionSection generalDescription={generalDescription} />
        <SpecificRequirementsSection specificRequirements={specificRequirements} />

        <div className="mt-8 text-xs text-gray-500">
          Generated by SRS PDF Generator — concise inputs expanded into a full SRS structure.
        </div>
      </div>
    </div>
  );
}
